<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Javascript Errors</title>
</head>
<body>
	<h3>JavaScript Errors</h3>
	<p><b>Throw, and Try...Catch...Finally</b>
	The try statement defines a code block to run (to try).
	The catch statement defines a code block to handle any error.
	The finally statement defines a code block to run regardless of the result.
	The throw st-	atement defines a custom error.</p>
	<br><hr>

	<h3>Errors Will Happen!</h3>
	<p>When executing JavaScript code, different errors can occur. Errors can be coding errors made by the programmer, errors due to wrong input, and other unforeseeable things.</p>
	<p id="demo01"></p>
	<br><hr>

	<h3>JavaScript try and catch</h3>
	<p>The try statement allows you to define a block of code to be tested for errors while it is being executed. The catch statement allows you to define a block of code to be executed, if an error occurs in the try block. The JavaScript statements try and catch come in pairs:</p>
	<pre>
		try {
 	 		Block of code to try
		}
		catch(err) {
 	 		Block of code to handle errors
		}
	</pre>
	<h3>JavaScript Throws Errors</h3>
	<p>When an error occurs, JavaScript will normally stop and generate an error message.</p>
	<p>The technical term for this is: JavaScript will throw an exception (throw an error).</p>
	<br><hr>

	<h3>The throw Statement</h3>
	<p>The throw statement allows you to create a custom error. Technically you can throw an exception (throw an error). The exception can be a JavaScript String, a Number, a Boolean or an Object:</p>
	<p>throw "Too big";    // throw a text</p>
	<p>throw 500;    // throw a number</p>
	<br><hr>

	<h3>Input Validation Example</h3>
	<p>This example examines input. If the value is wrong, an exception (err) is thrown. The exception (err) is caught by the catch statement and a custom error message is displayed:</p>
	<p>Please input a number between 5 and 10:</p>
	<!-- <input type="text" id="demo"> -->
	<input id="demo" type="number" min="5" max="10" step="1">
	<button type="button" onclick="myFunction()">Test input</button>
	<p id="demo02"></p>
	<br><hr>

	<h3>The finally Statement</h3>
	<p>The finally statement lets you execute code, after try and catch, regardless of the result:</p>
	<pre>
		try {
  			Block of code to try
		}
		catch(err) {
  			Block of code to handle errors
		}
		finally {
 	 		Block of code to be executed regardless of the try / catch result
		}
	</pre>
	<br><hr>

	<h3>Range Error</h3>
	<p>A RangeError is thrown if you use a number that is outside the range of legal values. For example: You cannot set the number of significant digits of a number to 500.</p>
	<p>You cannot set the number of significant digits too high:</p>
	<p id="demo03"></p>
	<br><hr>

	<h3>Reference Error</h3>
	<p>A ReferenceError is thrown if you use (reference) a variable that has not been declared:</p>
	<p id="demo04"></p>
	<br><hr>

	<h3>Syntax Error</h3>
	<p>A SyntaxError is thrown if you try to evaluate code with a syntax error.</p>
	<p id="demo05"></p>
	<br><hr>

	<h3>Type Error</h3>
	<p>A TypeError is thrown if an operand or argument is incompatible with the type expected by an operator or function.</p>
	<p id="demo06"></p>
	<br><hr>

	<h3>URI (Uniform Resource Identifier) Error</h3>
	<p>A URIError is thrown if you use illegal characters in a URI function:</p>
	<p id="demo07"></p>

<script>
	// demo01
	try {
	 	adddlert("Welcome guest!");
	}
	catch(err) {
		document.getElementById("demo01").innerHTML = err.message;
	}

	// demo02
	function myFunction() {
		var message = document.getElementById("demo02");
		message.innerHTML = "";
		let x = document.getElementById("demo").value;
		try{
			if(x.trim() == "") throw "empty";
			if(isNaN(x)) throw "Not a Number";
			x = Number(x);
			if(x < 35) throw "too low";
			if(x > 65) throw "too high";
		}
		catch(err) {
			message.innerHTML = "Input is " + err;
		}
	}

	// demo03
	let num = 1;
	try {
		num.toPrecision(500);
	}
	catch (err) {
		document.getElementById("demo03").innerHTML = err.name;
	}

	// demo04
	let a = 5;
	try {
		a = b + 1; 
	}
	catch (err) {
		document.getElementById("demo04").innerHTML = err.name;
	}

	// demo05
	try {
  		eval("alert('Hello)");
	}
	catch(err) {
  		document.getElementById("demo05").innerHTML = err.name;
	}

	// demo06
	let num02 = 1;
	try {
		num.toUpperCase();
	}
	catch(err) {
		document.getElementById("demo06").innerHTML = err.name;
	}

	// demo07
	try {
		decodeURI("%%%%");
	}
	catch(err){
		document.getElementById("demo07").innerHTML = err.name;
	}
</script>
</body>
</html>